# Generated by Django 3.0 on 2019-12-07 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sale_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('patient', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.AddField(
            model_name='sale',
            name='odoomodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.OdooModel'),
            preserve_default=False,
        ),
    ]
