# Generated by Django 3.0 on 2019-12-07 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='date_update',
        ),
        migrations.AddField(
            model_name='odoomodel',
            name='configurator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='odoomodel',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
