# Generated by Django 3.0 on 2019-12-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191207_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odoomodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
