# Generated by Django 3.0 on 2019-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoomodel',
            name='state_value',
            field=models.IntegerField(default=0),
        ),
    ]
