# Generated by Django 3.0 on 2019-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_odoomodel_state_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoomodel',
            name='content_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
