# Generated by Django 3.0 on 2019-12-10 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_odoomodel_content_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoomodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='odoomodel',
            name='date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='odoomodel',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='odoomodel',
            name='date_test',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
