# Generated by Django 3.0 on 2019-12-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_reportsaleproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsaleproduct',
            options={'ordering': ('-date_begin',)},
        ),
    ]
